# NumPy 

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Numpy is also incredibly fast because of it's bindings to C libraries. Here's a stackoverflow answer to why we should use numpy array instead of list: [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Installation

**Conda Installation**
    
    conda install numpy
    
**Other methods: [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## import numpy library as np

In [1]:
import numpy as np

For basic we can use Numpy to generate:
* vectors
* arrays
* matrices,
* number generation. 

# Numpy Arrays

NumPy arrays: 
* vectors and matrices. 
* Vectors are strictly 1-d arrays 
* Matrices are 2-d 
* Though matrices can have 1 row and 1 column with 1 element


## Creating vector

### From a Python List

In [2]:
py_list = [1,2,3, 4]
py_list

[1, 2, 3, 4]

In [3]:
np.array(py_list)

array([1, 2, 3, 4])

## Creating matrix

### From a Python List of List

In [4]:
py_matrix = [[1,2,3, 4],[5,6, 7, 8],[9, 10, 11, 12]]
py_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [5]:
np.array(py_matrix)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### from built-in methods

### numpy.arange([start, ]stop, [step, ]dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.


In [6]:
np.arange(1,10) # return number between 1 to 10, step is optional and by default it's 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,11,2) # here step is 2

array([1, 3, 5, 7, 9])

NOTE: start is inclusive, stop is exclusive

### numpy.zeros(shape, dtype=float, order='C')
Return a new array of given shape and type, filled with zeros.

Array of zeros with the given shape, dtype, and order.


In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

### numpy.ones(shape, dtype=None, order='C')
Return a new array of given shape and type, filled with ones.

Array of ones with the given shape, dtype, and order.


In [10]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [11]:
np.ones((5, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

Return evenly spaced numbers over a specified interval.


In [12]:
np.linspace(1, 10, 3)

array([  1. ,   5.5,  10. ])

In [13]:
np.linspace(0,1,50)

array([ 0.        ,  0.02040816,  0.04081633,  0.06122449,  0.08163265,
        0.10204082,  0.12244898,  0.14285714,  0.16326531,  0.18367347,
        0.20408163,  0.2244898 ,  0.24489796,  0.26530612,  0.28571429,
        0.30612245,  0.32653061,  0.34693878,  0.36734694,  0.3877551 ,
        0.40816327,  0.42857143,  0.44897959,  0.46938776,  0.48979592,
        0.51020408,  0.53061224,  0.55102041,  0.57142857,  0.59183673,
        0.6122449 ,  0.63265306,  0.65306122,  0.67346939,  0.69387755,
        0.71428571,  0.73469388,  0.75510204,  0.7755102 ,  0.79591837,
        0.81632653,  0.83673469,  0.85714286,  0.87755102,  0.89795918,
        0.91836735,  0.93877551,  0.95918367,  0.97959184,  1.        ])

### numpy.eye(N, M=None, k=0, dtype=<type 'float'>, order='C')
```
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Creates an identity matrix
```

In [14]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## Creating Random Vectors or Matices

### numpy.random.rand(d0, d1, ..., dn)
Random values in a given shape.

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).


In [15]:
np.random.rand(5)

array([ 0.49595737,  0.91251441,  0.00418833,  0.15961107,  0.97123151])

In [16]:
np.random.rand(5,5)

array([[ 0.08538193,  0.41090883,  0.39199091,  0.85168504,  0.23385263],
       [ 0.60349254,  0.35130909,  0.595837  ,  0.04878838,  0.91557991],
       [ 0.59892963,  0.59076112,  0.98030291,  0.23828429,  0.31105647],
       [ 0.25891277,  0.73419803,  0.75306509,  0.24679236,  0.76416903],
       [ 0.43765632,  0.26820115,  0.66311614,  0.64438625,  0.52266303]])

### numpy.random.randn(d0, d1, ..., dn)

Return a sample (or samples) from the “standard normal” distribution.

If positive, int_like or int-convertible arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

In [17]:
np.random.randn(2)

array([-1.30280228, -0.49319155])

In [18]:
np.random.randn(5,5)

array([[ 0.90900677,  1.64022109, -1.35941909, -0.45016373, -0.0704613 ],
       [ 0.06365533, -0.23239485,  1.55763377, -0.93836382,  0.68233432],
       [-1.23625421, -0.29990295,  0.11679702, -0.1617815 , -0.58952081],
       [ 1.07752493,  0.18127593, -0.88669817,  2.14446281,  0.87710782],
       [-0.93470821, -0.24588648, -0.48261841, -0.83421422,  0.754299  ]])

### numpy.random.randint(low, high=None, size=None, dtype='l')
Return random integers from low (inclusive) to high (exclusive).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [19]:
np.random.randint(1,100)

2

In [20]:
np.random.randint(1,100,10)

array([17, 62, 30, 67, 39, 74, 58, 48, 79, 81])

## Array Attributes and Methods

In [21]:
arr = np.arange(25)
random_arr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
random_arr

array([20,  6,  1, 39, 11, 45, 44, 22, 34, 38])

## numpy.reshape(a, newshape, order='C')
Gives a new shape to an array without changing its data.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

NOTE: Here one should mantain the number of elements and the dimension of new array to be created

### ndarray.max(axis=None, out=None, keepdims=False)
Return the maximum along a given axis.

### ndarray.min(axis=None, out=None, keepdims=False)
Return the minimum along a given axis.

### numpy.argmin(a, axis=None, out=None)
Returns the indices of the minimum values along an axis.

### numpy.argmax(a, axis=None, out=None)
Returns the indices of the maximum values along an axis.

In [25]:
random_arr

array([20,  6,  1, 39, 11, 45, 44, 22, 34, 38])

In [26]:
random_arr.max()

45

In [27]:
random_arr.argmax()

5

In [28]:
random_arr.min()

1

In [29]:
random_arr.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets => 2D array
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.reshape(5,5).shape

(5, 5)

### dtype

You can also grab the data type of the object in the array:

In [35]:
arr.dtype

dtype('int64')