# NumPy Indexing and Selection


In [1]:
import numpy as np

In [2]:
# Create a vector/array
arr = np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing and Selection
This is simplest to python lists:

In [4]:
# Get a value at an index
arr[3]

4

In [5]:
# Get values in a range
arr[1:5]

array([2, 3, 4, 5])

In [6]:
#Get values in a range
arr[0:5]

array([1, 2, 3, 4, 5])

## Broadcasting

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.


In [7]:
# Setting a value with index range
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If we make the slice of the numpy array and change the value inside the slice using broadcasting we see that that also affects the original array.

In [9]:
slice_of_arr = arr[0:5]
slice_of_arr

array([1, 2, 3, 4, 5])

In [10]:
# Broadcast in Slice
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

NOTE: changes also occur in our original array.

In [11]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

i.e. data is not copied, it's only a view of the original array. This avoids memory problems.

In [12]:
# Explicitly copy a array
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a matrices

Format:
* **arr_2d[row][col]** 
* **arr_2d[row,col]**

In [15]:
arr_2d = np.array(([1, 2, 3],[4, 5, 6],[7, 8, 9]))

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# Indexing row
arr_2d[1]

array([4, 5, 6])

**arr_2d[row][col]** 

In [17]:
# Getting individual element
arr_2d[0][0]

1

**arr_2d[row, col]** 

In [18]:
# Getting individual element value
arr_2d[1,0]

4

## Slicing a matrices


In [19]:
# Shape (2,2) from top right corner

arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [20]:
#Set up matrix
arr_2d = np.zeros((10,10))

In [21]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [22]:
arr_2d.shape[1]

10

In [23]:
arr_2d[1]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
arr_2d[1] = 1 # Broadcasting

In [25]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [26]:
arr_len = arr_2d.shape[1]

In [27]:
#Set up array

for i in range(arr_len):
    arr_2d[i] = i
    
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Fancy indexing allows the following

In [28]:
arr_2d[[1, 3, 5, 7]]

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [29]:
# Allows in any order
arr_2d[[6, 8, 2, 5]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.]])

## Selection

In [30]:
arr = np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [31]:
arr > 8

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [32]:
bool_arr = arr > 8

In [33]:
bool_arr

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [34]:
arr[bool_arr]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Selection is used while working with pandas.